version: '3.8'
services:
  flask_server:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - ollama_server
    networks:
      - app-network
    environment:
      - OLLAMA_SERVER_URL=http://ollama_server:11435

  ollama_server:
    build: .
    image: ollama/ollama:latest
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11435:11434"
    networks:
      - app-network

volumes:
  ollama:

networks:
  app-network:
    driver: bridge
